### ISSUE TITLE
Is generating tweets but its not tweeting anything

### ISSUE THREAD

**Issue by 0smak** [drmonkeysee/mashup-twitter-bot#1]
I setted the bot and its generating tweets, but the bot didnt tweet anything yet

**Comment by drmonkeysee** [comment]
yeah i never got around to writing the code that posts the tweets themselves. the markov output was inconsistent enough i didn't want it just posting nonsense.

feel free to fork this and play around with it. reviewing the code i think you would add the tweet-posting code around here: https://github.com/drmonkeysee/mashup-twitter-bot/blob/f09d86cb4a7cd053d8251958c86a9fcc195101a7/lib/tweetbot.js#L29 using the [Twit nodejs package](https://www.npmjs.com/package/twit) included in the dependencies (same package i use to read the tweet streams).

**Comment by 0smak** [comment]
Thanks, I'll play with your code!
